"""create student exam and journal tables

Revision ID: 78befe4ba92a
Revises: 
Create Date: 2026-08-30 00:03:34.327445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78befe4ba92a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=16), nullable=False),
    sa.Column('exam_name', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_exams_source_id'), 'calendar_exams', ['source_id'], unique=False)
    op.create_table('exam_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=16), nullable=False),
    sa.Column('exam_name', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_readable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_rules_document_sha256'), 'exam_rules', ['document_sha256'], unique=False)
    op.create_index(op.f('ix_exam_rules_source_id'), 'exam_rules', ['source_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('origin_url', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('kind_reason', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_kind'), 'source_documents', ['kind'], unique=False)
    op.create_index(op.f('ix_source_documents_sha256'), 'source_documents', ['sha256'], unique=True)
    op.create_index(op.f('ix_source_documents_source_id'), 'source_documents', ['source_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=8), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('is_pwbd', sa.Boolean(), nullable=False),
    sa.Column('is_ex_serviceman', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('degree', sa.String(length=64), nullable=False),
    sa.Column('stream', sa.String(length=96), nullable=True),
    sa.Column('completed_year', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_name', sa.Text(), nullable=False),
    sa.Column('source_id', sa.String(length=16), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('is_approximate', sa.Boolean(), nullable=False),
    sa.Column('citation_page', sa.Integer(), nullable=True),
    sa.Column('citation_quote', sa.Text(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadlines_due_on'), 'deadlines', ['due_on'], unique=False)
    op.create_index(op.f('ix_deadlines_student_id'), 'deadlines', ['student_id'], unique=False)
    op.create_table('journal_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sources_checked', sa.Integer(), nullable=False),
    sa.Column('notifications_seen', sa.Integer(), nullable=False),
    sa.Column('documents_downloaded', sa.Integer(), nullable=False),
    sa.Column('rules_evaluated', sa.Integer(), nullable=False),
    sa.Column('citations_verified', sa.Integer(), nullable=False),
    sa.Column('changes_found', sa.Integer(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('seconds_taken', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_runs_student_id'), 'journal_runs', ['student_id'], unique=False)
    op.create_table('journal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('worth_telling', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['journal_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_events_run_id'), 'journal_events', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_events_run_id'), table_name='journal_events')
    op.drop_table('journal_events')
    op.drop_index(op.f('ix_journal_runs_student_id'), table_name='journal_runs')
    op.drop_table('journal_runs')
    op.drop_index(op.f('ix_deadlines_student_id'), table_name='deadlines')
    op.drop_index(op.f('ix_deadlines_due_on'), table_name='deadlines')
    op.drop_table('deadlines')
    op.drop_table('students')
    op.drop_index(op.f('ix_source_documents_source_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_sha256'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_kind'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_exam_rules_source_id'), table_name='exam_rules')
    op.drop_index(op.f('ix_exam_rules_document_sha256'), table_name='exam_rules')
    op.drop_table('exam_rules')
    op.drop_index(op.f('ix_calendar_exams_source_id'), table_name='calendar_exams')
    op.drop_table('calendar_exams')
    # ### end Alembic commands ###
