"""add qualification ladder

Revision ID: c7e142600563
Revises: aa14e853243c
Create Date: 2026-08-30 17:55:36.268922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e142600563'
down_revision: Union[str, Sequence[str], None] = 'aa14e853243c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=24), nullable=False),
    sa.Column('board_or_university', sa.String(length=160), nullable=True),
    sa.Column('college', sa.String(length=160), nullable=True),
    sa.Column('stream', sa.String(length=120), nullable=True),
    sa.Column('marks_kind', sa.String(length=16), nullable=False),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('cgpa_scale', sa.Float(), nullable=True),
    sa.Column('passed_year', sa.Integer(), nullable=True),
    sa.Column('passed_on', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('current_semester', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'level', name='uq_student_level')
    )
    op.create_index(op.f('ix_qualifications_student_id'), 'qualifications', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualifications_student_id'), table_name='qualifications')
    op.drop_table('qualifications')
    # ### end Alembic commands ###
